### ISSUE TITLE
# meaning？

### ISSUE THREAD

**Issue by chushuai** [meedan/alegre#29]
SELECT images.*, BIT_COUNT(phash # :phash)

**Comment by computermacgyver** [comment]
# is the bitwise XOR operator in postgres

> The PostgreSQL Bitwise XOR ( # ) operator is similar to OR operator. It compares corresponding bits for each operand and produces a 1 when either but not both bits is 1 otherwise it returns 0.

https://www.postgresql.org/docs/9.4/functions-bitstring.html

In order to scale the matching efficiently, each image hash (a binary string of zeros and ones) is converted to a big integer. These integers are compared bitwise using XOR (#) and then the number of  ones are counted with BIT_COUNT(...). This is the sum of the total number of binary digits that differ between the two images being compared and is known as the Hamming distance.
